version: '3.8'

services:
  file-downloader:
    image: file-downloader:latest
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./your-path:/data
    environment:
      TARGET_DIR: "/data"
